version: '3.4'

services:
  api:
    restart: always
    image: cqrs-es-test-api
    build:
      context: .
    volumes:
      - ./apps:/app/apps
      - ./libs:/app/libs
    ports:
      - 3000:3000
    env_file: .env.example
    command: npx nest start api -w

  user:
    restart: always
    image: cqrs-es-test-user
    build:
      context: .
    volumes:
      - ./apps:/app/apps
      - ./libs:/app/libs
    env_file: .env.example
    command: npx nest start user -w

  notifications:
    restart: always
    image: cqrs-es-test-notifications
    build:
      context: .
    volumes:
      - ./apps:/app/apps
      - ./libs:/app/libs
    env_file: .env.example
    command: npx nest start notifications -w

  auth:
    restart: always
    image: cqrs-es-test-auth
    build:
      context: .
    volumes:
      - ./apps:/app/apps
      - ./libs:/app/libs
    env_file: .env.example
    command: npx nest start auth -w

  nats:
    restart: always
    image: nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222

  postgres:
    restart: always
    image: postgres:alpine
    env_file: .env.example
    ports:
      - 5432:5432
